# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from . import orders_pb2 as orders__pb2

GRPC_GENERATED_VERSION = "1.82.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in orders_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class OrderQueryServiceStub:
    """Service definition for internal order queries"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOrder = channel.unary_unary(
            "/orders.OrderQueryService/GetOrder",
            request_serializer=orders__pb2.GetOrderRequest.SerializeToString,
            response_deserializer=orders__pb2.OrderResponse.FromString,
            _registered_method=True,
        )
        self.GetTrades = channel.unary_unary(
            "/orders.OrderQueryService/GetTrades",
            request_serializer=orders__pb2.GetTradesRequest.SerializeToString,
            response_deserializer=orders__pb2.GetTradesResponse.FromString,
            _registered_method=True,
        )
        self.GetOrdersByUser = channel.unary_unary(
            "/orders.OrderQueryService/GetOrdersByUser",
            request_serializer=orders__pb2.GetOrdersByUserRequest.SerializeToString,
            response_deserializer=orders__pb2.GetOrdersByUserResponse.FromString,
            _registered_method=True,
        )
        self.GetTradesByUser = channel.unary_unary(
            "/orders.OrderQueryService/GetTradesByUser",
            request_serializer=orders__pb2.GetTradesByUserRequest.SerializeToString,
            response_deserializer=orders__pb2.GetTradesResponse.FromString,
            _registered_method=True,
        )


class OrderQueryServiceServicer:
    """Service definition for internal order queries"""

    def GetOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetTrades(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetOrdersByUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetTradesByUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_OrderQueryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetOrder": grpc.unary_unary_rpc_method_handler(
            servicer.GetOrder,
            request_deserializer=orders__pb2.GetOrderRequest.FromString,
            response_serializer=orders__pb2.OrderResponse.SerializeToString,
        ),
        "GetTrades": grpc.unary_unary_rpc_method_handler(
            servicer.GetTrades,
            request_deserializer=orders__pb2.GetTradesRequest.FromString,
            response_serializer=orders__pb2.GetTradesResponse.SerializeToString,
        ),
        "GetOrdersByUser": grpc.unary_unary_rpc_method_handler(
            servicer.GetOrdersByUser,
            request_deserializer=orders__pb2.GetOrdersByUserRequest.FromString,
            response_serializer=orders__pb2.GetOrdersByUserResponse.SerializeToString,
        ),
        "GetTradesByUser": grpc.unary_unary_rpc_method_handler(
            servicer.GetTradesByUser,
            request_deserializer=orders__pb2.GetTradesByUserRequest.FromString,
            response_serializer=orders__pb2.GetTradesResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "orders.OrderQueryService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "orders.OrderQueryService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class OrderQueryService:
    """Service definition for internal order queries"""

    @staticmethod
    def GetOrder(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/orders.OrderQueryService/GetOrder",
            orders__pb2.GetOrderRequest.SerializeToString,
            orders__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetTrades(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/orders.OrderQueryService/GetTrades",
            orders__pb2.GetTradesRequest.SerializeToString,
            orders__pb2.GetTradesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetOrdersByUser(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/orders.OrderQueryService/GetOrdersByUser",
            orders__pb2.GetOrdersByUserRequest.SerializeToString,
            orders__pb2.GetOrdersByUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetTradesByUser(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/orders.OrderQueryService/GetTradesByUser",
            orders__pb2.GetTradesByUserRequest.SerializeToString,
            orders__pb2.GetTradesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
