{
 "title": "API Gateway Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "API Gateway RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{exported_job=\"api-gateway\"}[1m])) by (http_target, http_method)",
     "legendFormat": "{{http_method}} {{http_target}}"
    }
   ]
  },
  {
   "title": "API Gateway Latency (P95 / P99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{exported_job=\"api-gateway\"}[1m])) by (le))",
     "legendFormat": "P95 Latency"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{exported_job=\"api-gateway\"}[1m])) by (le))",
     "legendFormat": "P99 Latency"
    }
   ]
  },
  {
   "title": "API Gateway 5xx Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{exported_job=\"api-gateway\", http_status_code=~\"4..|5..\"}[1m]))",
     "legendFormat": "4xx / 5xx Errors"
    }
   ]
  }
 ]
}