"""add filled_quantity

Revision ID: 5ec5aa7877cd
Revises: 0eef24a2b787
Create Date: 2026-07-08 10:09:33.790448

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ec5aa7877cd"
down_revision: str | Sequence[str] | None = "0eef24a2b787"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column("filled_quantity", sa.Float(), server_default="0.0", nullable=False),
    )

    # Add new enum values to PostgreSQL ENUM
    # Note: postgresql does not allow removing enum values (like EXECUTED) easily inside a transaction,
    # but we can add new ones.
    op.execute("ALTER TYPE orderstatuschoice ADD VALUE IF NOT EXISTS 'FILLED'")
    op.execute(
        "ALTER TYPE orderstatuschoice ADD VALUE IF NOT EXISTS 'PARTIALLY_FILLED'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "filled_quantity")
    # ### end Alembic commands ###
