"""Add balances

Revision ID: f226a5a57a19
Revises: 5eaaddb3d952b
Create Date: 2026-07-26 14:12:56.065099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f226a5a57a19'
down_revision: Union[str, Sequence[str], None] = '5eaaddb3d952b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('available', sa.Numeric(), nullable=False),
    sa.Column('locked', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'currency', name='uix_user_currency')
    )
    op.create_index(op.f('ix_balances_currency'), 'balances', ['currency'], unique=False)
    op.create_index(op.f('ix_balances_user_id'), 'balances', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_balances_user_id'), table_name='balances')
    op.drop_index(op.f('ix_balances_currency'), table_name='balances')
    op.drop_table('balances')
    # ### end Alembic commands ###
